/** The generated plans block in CLAUDE.md: one block, whatever marker an older copy of the system wrote. */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { box, plan } from "./_helpers.mjs";

describe("the CLAUDE.md plans block", () => {
  it("replaces a block written by an older copy of the system instead of adding a second one beside it", () => {
    const root = box("planrails-block-");
    writeFileSync(join(root, "CLAUDE.md"), "# t\n\n<!-- plans:begin — generated by scripts/plan/plan.mjs; do not hand-edit this block -->\n_No active plans._\n<!-- plans:end -->\n\n## Project management\n\nkeep this paragraph\n");
    plan(root, "new", "demo", "--title", "Demo plan under test");
    plan(root, "gate", "add", "demo", "--question", "does true exit zero in this shell", "--not", "anything about the work itself",
      "--command", "true", "--wrong", "true is always true, which is the point", "--known-fail", "false", "--known-fail-why", "a false command must fail here");
    plan(root, "task", "add", "demo", "--title", "The only task of the demo plan", "--gate", "G1");
    plan(root, "gate", "verify", "demo", "--all");
    plan(root, "activate", "demo");
    const md = readFileSync(join(root, "CLAUDE.md"), "utf8");
    assert.equal(md.split("<!-- plans:begin").length - 1, 1, md);
    assert.ok(md.includes("**demo**") && md.includes("keep this paragraph"), md);
    assert.ok(!md.includes("scripts/plan/plan.mjs"), md);
    assert.ok(md.indexOf("plans:begin") < md.indexOf("## Project management"), md);
  });
});
