/**
 * The ONE block the plan system owns in CLAUDE.md.
 *
 * CLAUDE.md is always in context, so the pointer to an active plan lives there
 * and nowhere else. The block is generated: `activate` adds a line, `close`
 * removes it, and `validate --all` fails if the block and the active plans
 * disagree. That drift check is why a stale pointer cannot survive — the exact
 * failure CLAUDE.md § ♻️ describes ("the line that used to stand here sent every
 * session to a block saying 'coverage done'").
 *
 * The block carries NO counts or dates: those would change on every log entry
 * and turn CLAUDE.md into a noisy diff. Live state comes from the brief.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";

export const BEGIN = "<!-- plans:begin — generated by src/plan/plan.mjs; do not hand-edit this block -->";
export const END = "<!-- plans:end -->";

export function renderBlock(activePlans) {
  const lines = [BEGIN];
  if (activePlans.length) {
    lines.push("**▶ ACTIVE PLANS — a SessionStart hook injects each plan's brief; if you do not see it, run `npx planrails brief` before any work on these.** Record progress with `plan log`, findings with `plan learn`, choices with `plan decide`; mark a task done only through `plan task done` (it runs the gate). Guide: docs/PLANNING_GUIDE.md.");
    for (const p of activePlans) lines.push(`- **${p.id}** — ${p.title} — \`.project-management/plans/${p.id}/PLAN.md\``);
  } else {
    lines.push("_No active plans. Create one with `/plan <raw plan>` or `npx planrails new <id> --title \"…\"` (docs/PLANNING_GUIDE.md)._");
  }
  lines.push(END);
  return lines.join("\n");
}

/** Any begin marker counts, whatever generator name it carries: an older copy of this system wrote a different one, and a second block must never be added beside it. */
const BEGIN_PREFIX = "<!-- plans:begin";
export function readBlock(md) {
  const a = md.indexOf(BEGIN_PREFIX); const b = md.indexOf(END);
  if (a === -1 || b === -1 || b < a) return null;
  return md.slice(a, b + END.length);
}
/** How many blocks the file holds. More than one is a merge accident; validate fails on it. */
export function blockCount(md) { return md.split(BEGIN_PREFIX).length - 1; }

/** Plan ids currently listed in the block (for the drift check). */
export function idsInBlock(md) {
  const block = readBlock(md);
  if (!block) return null;
  return [...block.matchAll(/^- \*\*([a-z0-9-]+)\*\*/gm)].map((m) => m[1]);
}

/** Write the block in place; if absent, insert it before "## Project management", else append. Returns true if the file changed. */
export function writeBlock(path, activePlans) {
  const md = existsSync(path) ? readFileSync(path, "utf8") : "";
  const block = renderBlock(activePlans);
  const existing = readBlock(md);
  let next;
  if (existing) {
    // Every block is taken out (a merge can leave two, even two identical ones); the first one's place gets the
    // fresh block. Function replacers throughout: a plain string replacement would $-expand a title holding "$&".
    const HOLE = "\u0000plans-block\u0000";
    next = md; let blk; let first = true;
    while ((blk = readBlock(next)) !== null) { next = next.replace(blk, () => (first ? HOLE : "")); first = false; }
    next = next.replace(HOLE, () => block).replace(/\n{3,}/g, "\n\n");
  } else {
    const anchor = md.search(/^## Project management\s*$/m);
    next = anchor === -1 ? `${md.replace(/\s*$/, "")}\n\n${block}\n` : `${md.slice(0, anchor)}${block}\n\n${md.slice(anchor)}`;
  }
  if (next === md) return false;
  writeFileSync(path, next);
  return true;
}
